### ISSUE TITLE
AWS API Deploy practices

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss-labs/identifier-service#23]
Swagger vs other, approaches, etc.

**Comment by eefahy** [comment]
readings on how to deploy the API via swagger+terraform:
https://github.com/terraform-providers/terraform-provider-aws/pull/1197 (last comment gives examples on how to bring in the swagger file to the `api_gateway_rest_api` resource)
https://www.terraform.io/docs/providers/aws/r/api_gateway_rest_api.html

**Comment by cmharlow** [comment]
This issue was moved to sul-dlss-labs/dataOps#36
