### ISSUE TITLE
Fake out Creating a new DRUID on a single call for single identifier action

### ISSUE THREAD

**Issue by cmharlow** [sul-dlss-labs/identifier-service#42]
Have the template in the swagger.json spec currently. There are some additions to DRUID format, should we try to capture here? (for example, I don't believe DRUIDs can contain vowels).

**Comment by jcoyne** [comment]
@cmh2166 this should all be handled https://github.com/sul-dlss-labs/identifier-service/pull/31/files#diff-2b9ee5396f9b5f0b0d129ecfa6efd95dR10

**Comment by cmharlow** [comment]
okay, then close it if covered in current code or PR. i'm also wondering if the parameters.default field worked in the spec.

**Comment by jcoyne** [comment]
@cmh2166 yeah, it looks like that default is set.  I added a ticket to explore that more: https://github.com/sul-dlss-labs/identifier-service/issues/48
